[package]
name = "c_hash_sig_crust"
version = "0.2.0"
edition = "2021"

[lib]
name = "c_hash_sig_crust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
backend = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "fd8814045deb0ef8fcad4c9f4b1250ee33f7dd01" }
cpp = { path = "../cpp" }
leansig = { git = "https://github.com/leanEthereum/leanSig.git", branch = "devnet4" }
rand = "0.10.0"
rec_aggregation = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "fd8814045deb0ef8fcad4c9f4b1250ee33f7dd01" }
serde_json = "1.0"
ssz = { package = "ethereum_ssz", version = "0.10.0" }

[build-dependencies]
build-helper = { path = "../build-helper" }
