[package]
name = "c_hash_sig_crust"
version = "0.2.0"
edition = "2021"

[lib]
name = "c_hash_sig_crust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
backend = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "f2ead87b771439803891f5d4f7c68ab47da48d9d" }
cpp = { path = "../cpp" }
leansig = { git = "https://github.com/leanEthereum/leanSig.git", branch = "devnet4" }
leansig_fast_keygen = { git = "https://github.com/TomWambsgans/leanSig.git", branch = "devnet4-fast-keygen" }
rand = "0.10.0"
rec_aggregation = { git = "https://github.com/leanEthereum/leanMultisig.git", rev = "f2ead87b771439803891f5d4f7c68ab47da48d9d" }
serde_json = "1.0"
ssz = { package = "ethereum_ssz", version = "0.10.0" }

[build-dependencies]
build-helper = { path = "../build-helper" }
